// Mock nation data for testing when API key is not available
export const mockNationData = {
  "145633": {
    id: "145633",
    nation_name: "Riftopia",
    leader_name: "DevCodeRift",
    alliance_id: "1234",
    alliance: {
      id: "1234",
      name: "Test Alliance"
    },
    war_policy: "Attrition",
    domestic_policy: "Manifest Destiny",
    color: "blue",
    num_cities: 15,
    score: 2500.50,
    population: 1250000,
    soldiers: 125000,
    tanks: 3500,
    aircraft: 800,
    ships: 150,
    missiles: 25,
    nukes: 5,
    money: 50000000,
    coal: 5000,
    oil: 8000,
    uranium: 500,
    iron: 3000,
    bauxite: 2500,
    lead: 1200,
    gasoline: 6500,
    munitions: 4500,
    steel: 2800,
    aluminum: 1800,
    food: 15000,
    government_type: "Democracy",
    economic_policy: "Capitalism",
    social_policy: "Liberal",
    cities: [
      {
        id: "1",
        name: "Capital City",
        infrastructure: 2000,
        land: 1000,
        powered: true,
        barracks: 5,
        factory: 5,
        hangar: 3,
        drydock: 1,
        coal_power: 2,
        oil_power: 1,
        nuclear_power: 1,
        wind_power: 0,
        coal_mine: 3,
        oil_well: 2,
        uranium_mine: 1,
        iron_mine: 2,
        bauxite_mine: 2,
        lead_mine: 1,
        farm: 4,
        aluminum_refinery: 1,
        steel_mill: 1,
        oil_refinery: 1,
        munitions_factory: 1,
        police_station: 1,
        hospital: 1,
        recycling_center: 1,
        subway: 1,
        supermarket: 1,
        bank: 1,
        shopping_mall: 1,
        stadium: 1
      },
      {
        id: "2",
        name: "Industrial Hub",
        infrastructure: 1800,
        land: 950,
        powered: true,
        barracks: 5,
        factory: 5,
        hangar: 2,
        drydock: 0,
        coal_power: 1,
        oil_power: 2,
        nuclear_power: 0,
        wind_power: 1,
        coal_mine: 2,
        oil_well: 3,
        uranium_mine: 0,
        iron_mine: 3,
        bauxite_mine: 2,
        lead_mine: 1,
        farm: 3,
        aluminum_refinery: 2,
        steel_mill: 2,
        oil_refinery: 2,
        munitions_factory: 2,
        police_station: 1,
        hospital: 1,
        recycling_center: 1,
        subway: 1,
        supermarket: 1,
        bank: 1,
        shopping_mall: 0,
        stadium: 0
      }
    ]
  },
  "662952": {
    id: "662952",
    nation_name: "Emerald Republic",
    leader_name: "TestLeader1",
    alliance_id: "5678",
    alliance: {
      id: "5678",
      name: "Green Alliance"
    },
    war_policy: "Blitzkrieg",
    domestic_policy: "Urbanization",
    color: "green",
    num_cities: 12,
    score: 1850.25,
    population: 980000,
    soldiers: 98000,
    tanks: 2800,
    aircraft: 650,
    ships: 120,
    missiles: 18,
    nukes: 3,
    money: 35000000,
    coal: 4200,
    oil: 6500,
    uranium: 350,
    iron: 2500,
    bauxite: 2000,
    lead: 900,
    gasoline: 5200,
    munitions: 3500,
    steel: 2200,
    aluminum: 1500,
    food: 12000,
    government_type: "Parliamentary Democracy",
    economic_policy: "Mixed Economy",
    social_policy: "Moderate",
    cities: [
      {
        id: "3",
        name: "Green Capital",
        infrastructure: 1750,
        land: 875,
        powered: true,
        barracks: 4,
        factory: 4,
        hangar: 2,
        drydock: 1,
        coal_power: 1,
        oil_power: 1,
        nuclear_power: 1,
        wind_power: 1,
        coal_mine: 2,
        oil_well: 2,
        uranium_mine: 1,
        iron_mine: 2,
        bauxite_mine: 1,
        lead_mine: 1,
        farm: 3,
        aluminum_refinery: 1,
        steel_mill: 1,
        oil_refinery: 1,
        munitions_factory: 1,
        police_station: 1,
        hospital: 1,
        recycling_center: 1,
        subway: 1,
        supermarket: 1,
        bank: 1,
        shopping_mall: 1,
        stadium: 0
      }
    ]
  },
  "701263": {
    id: "701263",
    nation_name: "Azure Federation",
    leader_name: "TestLeader2",
    alliance_id: "9999",
    alliance: {
      id: "9999",
      name: "Blue Coalition"
    },
    war_policy: "Fortress",
    domestic_policy: "Technological Advancement",
    color: "blue",
    num_cities: 18,
    score: 3200.75,
    population: 1650000,
    soldiers: 165000,
    tanks: 4500,
    aircraft: 1000,
    ships: 200,
    missiles: 35,
    nukes: 8,
    money: 75000000,
    coal: 6500,
    oil: 10000,
    uranium: 750,
    iron: 4000,
    bauxite: 3500,
    lead: 1800,
    gasoline: 8500,
    munitions: 6000,
    steel: 3800,
    aluminum: 2500,
    food: 20000,
    government_type: "Federal Republic",
    economic_policy: "Free Market",
    social_policy: "Conservative",
    cities: [
      {
        id: "4",
        name: "Azure Metropolis",
        infrastructure: 2200,
        land: 1100,
        powered: true,
        barracks: 5,
        factory: 5,
        hangar: 4,
        drydock: 2,
        coal_power: 2,
        oil_power: 2,
        nuclear_power: 2,
        wind_power: 0,
        coal_mine: 3,
        oil_well: 3,
        uranium_mine: 2,
        iron_mine: 3,
        bauxite_mine: 3,
        lead_mine: 2,
        farm: 5,
        aluminum_refinery: 2,
        steel_mill: 2,
        oil_refinery: 2,
        munitions_factory: 2,
        police_station: 1,
        hospital: 2,
        recycling_center: 1,
        subway: 2,
        supermarket: 2,
        bank: 2,
        shopping_mall: 1,
        stadium: 1
      },
      {
        id: "5",
        name: "Tech Valley",
        infrastructure: 2000,
        land: 1000,
        powered: true,
        barracks: 5,
        factory: 5,
        hangar: 3,
        drydock: 1,
        coal_power: 1,
        oil_power: 1,
        nuclear_power: 1,
        wind_power: 2,
        coal_mine: 2,
        oil_well: 2,
        uranium_mine: 1,
        iron_mine: 2,
        bauxite_mine: 2,
        lead_mine: 1,
        farm: 4,
        aluminum_refinery: 2,
        steel_mill: 2,
        oil_refinery: 1,
        munitions_factory: 2,
        police_station: 1,
        hospital: 1,
        recycling_center: 2,
        subway: 1,
        supermarket: 1,
        bank: 1,
        shopping_mall: 1,
        stadium: 1
      }
    ]
  }
};

export function getMockNationData(nationId: string) {
  return mockNationData[nationId as keyof typeof mockNationData] || null;
}

export function isApiKeyConfigured(): boolean {
  const serverKey = process.env.PW_BOT_API_KEY;
  const publicKey = process.env.NEXT_PUBLIC_PW_API_KEY;
  
  const apiKey = typeof window === 'undefined' 
    ? serverKey || publicKey
    : publicKey;
  
  const isConfigured = !!(apiKey && apiKey !== 'your_pw_api_key_here' && apiKey.length > 10);
  
  console.log('Mock data check:', {
    isServer: typeof window === 'undefined',
    hasServerKey: !!serverKey,
    hasPublicKey: !!publicKey,
    apiKeyConfigured: isConfigured,
    keyPreview: apiKey ? `${apiKey.substring(0, 6)}...` : 'none'
  });
  
  return isConfigured;
}
